
const SERVICEKEY = process.env.NEXT_PUBLIC_SERVICEID;
const TEMPLATEKEY = process.env.NEXT_PUBLIC_TEMPLATEID;
const PUBLICKEY = process.env.NEXT_PUBLIC_PUBLICKEY;
const PRIVATEKEY = process.env.NEXT_PUBLIC_PRIVATEKEY;


export {SERVICEKEY, TEMPLATEKEY, PUBLICKEY, PRIVATEKEY};